### PR TITLE
Fix typos in pdfa.sh

### PR DESCRIPTION
**Pull request by petrkasp**

### CODE REVIEW

**Review by exaexa — APPROVED** [review]
lgtm, thanks!

**Comment by exaexa** [comment]
just curious, is this some kindof automated spellcheck? I got similar commits for like 4 of my repos recently so kinda wondering. :D

**Comment by petrkasp** [comment]
haha no. I was just going through the files and reading the note and the "can not" made me think for a while what was meant, only to realize that it was a typo. I saw a few others so I submitted the pull request. So no automatic spellcheck, perhaps it's just the season of pedants lol

**Comment by exaexa** [comment]
ok cool :) Thanks a lot again!

**Comment by exaexa** [comment]
PS I'm somehow realizing that the stuff in the template might be full of similar mistakes 😅

**Comment by petrkasp** [comment]
I'll be going through it anyway, so I'll try to fix these if I see any. Thanks for the work on the template!

**Pull request merged**
